version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sql_injection
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"
    environment:
      service_email: dzjob10@gmail.com
      service_password: ifvwyawfscccgqif
    depends_on:
      - mysql
    networks:
      - my_network

  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth_service
      - prediction_service
      - chatbot_service
    networks:
      - my_network

  prediction_service:
    build: ./prediction_service
    ports:
      - "8002:8002"
    networks:
      - my_network

  chatbot_service:
    build:
      context: ./chatbot_service
      dockerfile: Dockerfile  # تأكد أن لديك ملف Dockerfile داخل chatbot_service
    container_name: chatbot_service
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"  # يتم تحميل المفتاح من ملف .env
    ports:
      - "8003:8003"
    networks:
      - my_network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api_gateway
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
